spring:
  datasource:
    url: ${CRM_DB_URL:jdbc:postgresql://localhost:5432/crm}
    username: ${CRM_DB_USERNAME:postgres}
    password: ${CRM_DB_PASSWORD:postgres@123}

application:
  upload-directory: ${PHOTO_UPLOAD_DIRECTORY:./upload/}