spring:
  application:
    name: CRM Service
  datasource:
    url: ${CRM_DB_URL}
    username: ${CRM_DB_USERNAME}
    password: ${CRM_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
  flyway:
    locations: classpath:/db/migration
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        region: ${AWS_REGION:us-east-1}

springdoc:
  swagger-ui:
    operationsSorter: method

application:
  s3:
    bucket-name: ${S3_BUCKET_NAME}